---
language: python
python: 
  - "2.7"
  - "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install dependences
  - pip install ansible flake8

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml
  - flake8 lookup_plugins/*.py

